### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by saundefined**
- [x] Let's keep "Branding" link only in the footer.
- [x] I think we do not need Github button under the hero block on the main page.
- [x] Let's rename "Blog" to "News" and add "Latest news" section with a couple of blog posts similar to https://kotlinfoundation.org/
- [x] Let's keep it one column throughout the whole page. And I really like the idea of having block with results –> Let's make it similar to https://kotlinfoundation.org/ and also add a button linked to the report with the text "2022 Impact Report" https://thephp.foundation/blog/2022/11/22/transparency-and-impact-report-2022/
- [x] Speakers - embed not blog posts, just page
- [x] Speakers page is now sort of a blog – this seems overcomplicated to me. Let's make just a "cards" page with embeded videos and info about speakers.

### CODE REVIEW

**Comment by pronskiy** [comment]
Overall looks great! @saundefined, thank you for leading this initiative.

I have a few requests/comments.

- Let's keep "Branding" link only in the footer.
- I think we do not need Github button under the hero block on the main page.
- Speakers - embed not blog posts, just page
- Let's rename "Blog" to "News" and add "Latest news" section with a couple of blog posts similar to https://kotlinfoundation.org/
- Let's keep it one column throughout the whole page. And I really like the idea of having block with results –> Let's make it similar to https://kotlinfoundation.org/ and also add a button linked to the report with the text "2022 Impact Report" https://thephp.foundation/blog/2022/11/22/transparency-and-impact-report-2022/
- Speakers page is now sort of a blog – this seems overcomplicated to me. Let's make just a "cards" page with embeded videos and info about speakers.

**Comment by saundefined** [comment]
@pronskiy thanks for the review, updated some points.

- What about php.net link after hero? It looks lonely now :)
- Updated News, but the links remain on the `/blog` so as not to generate a lot of 404s... what do you think?

--
Clarification on Speakers: as I understand, we drop the detail page, but the embedding is not very clear.

If immediately output YouTube player for all elements, it seems that with a huge number of items it will be slow.

Maybe make cards with the speakers and buttons for external resources: materials, video; for future conferences, we can display links to registration, what do you think?

**Comment by pronskiy** [comment]
> What about php.net link after hero? It looks lonely now :)

Yeah, it does not look good there. Let's add it in the top menu to the right of the "Get Involved"? 

> Updated News, but the links remain on the /blog so as not to generate a lot of 404s... what do you think?

Sounds good.

> If immediately output YouTube player for all elements, it seems that with a huge number of items it will be slow.
> 
> Maybe make cards with the speakers and buttons for external resources: materials, video; for future conferences, we can display links to registration, what do you think?

Initially I meant just using iframe that YouTube provides. I think it should be fine because we will not have too many of them. But if we do later, then we could display preview image and link to youtube.

I like the idea of having cards with the following:
- Title
- Speaker names
- Conference name, year, and location

**Comment by saundefined** [comment]
> Initially I meant just using iframe that YouTube provides.

A little update, what do you think?

**Comment by saundefined** [comment]
@pronskiy fixed:
- Top-nav links underlined
- php.net lowercased, added external link icon
- Added shadow to header
- Added new page "Foundation" – we can put into it text blocks (similar Ruby)
- Rework a little News section
- Speakers => Presentations
- Temporary hide Get involved page
- Branding is simple md page now 

Remains to be fixed:
- Align Supporters to center

**Comment by sebastianbergmann** [comment]
What do we need to do to publish these changes? IMO, this is a great improvement over what's currently live. Once these changes are live, we can of course iterate further.

**Comment by pronskiy** [comment]
@sebastianbergmann, agree, I have some slight improvements to it which I'm going to push and merge this right after.

**Comment by pronskiy** [comment]
@saundefined thank you 🙏

**Pull request merged**
